# Generated by Django 4.2.13 on 2024-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
