# Generated by Django 4.2.5 on 2023-12-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_mymodel_csv_file_mymodel_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='csv_data',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='json_data',
        ),
    ]
