# Generated by Django 4.2.5 on 2024-03-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
