# Generated by Django 4.2.13 on 2024-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_chatapp", "0005_message_delete_chat_delete_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
