# Generated by Django 4.2.13 on 2024-08-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("x_app", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
    ]
